### ISSUE TITLE
Web : ranking computing

### ISSUE THREAD

**Issue by sdaviet** [jomarin38/F3FChrono#67] opened 2020-03-28 08:34 UTC
Could you check f3f_ranking computing with a contest where you change the started bib Day+1 ?
I have an error for my part.

**Comment by jomarin38** [comment] 2020-03-28 08:43
OK, I will check

**Comment by jomarin38** [comment] 2020-03-28 09:13
What did you do excatcly ?
On Puy de Manse competition, I set the strt bib to 6, then used the web interface to complete the round and there was no problem in the web interface.
However, there was an error in the link included in the header of round view page, which should be corrected by #68

**Comment by sdaviet** [comment] 2020-03-28 09:22
I have this error on my test contest. It's possibly a bad contest data in the BDD.
[KeyError at _f3franking_event_view.zip](https://github.com/jomarin38/F3FChrono/files/4396884/KeyError.at._f3franking_event_view.zip)

**Comment by jomarin38** [comment] 2020-03-28 09:37
I am not able to reproduce it, but from the error message, it should be fixed by #69

**Comment by sdaviet** [comment] 2020-03-28 11:30
It work now. thank.

**Closed** 2020-03-28 11:29 UTC
